language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  include:
    - stage: deploy docs
      os: linux
      julia: 1.2
      script:
        - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterMarkdown")'
        - julia --project --color=yes docs/make.jl
      after_success: skip
        
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
